version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: masterdsa-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=masterdsa
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d masterdsa"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data:
